x-backend-common: &backend-common
  build:
    context: ./ # ./ resolves to ./backend because it is is used as base file
    dockerfile: Dockerfile
  env_file:
    - ./.env.demo
  expose:
    - 8000
  depends_on:
    redis:
      condition: service_healthy
    rabbitmq:
      condition: service_healthy
    mongo1:
      condition: service_healthy    
    mongo2:
      condition: service_healthy
    mongo3:
      condition: service_healthy
  restart: unless-stopped

services:
  backend:
    container_name: image_resize_backend
    <<: *backend-common

  celery_worker:
    container_name: image_resize_worker
    <<: *backend-common
    command: celery -A src.celery_app.worker.celery worker --loglevel=info

  nginx:
    container_name: image_resize_proxy
    build:
      context: ../ # ./ resolves to ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 80:80
      - 9000:9000 # for the minio endpoint
    volumes:
      - ../nginx.conf:/etc/nginx/nginx.conf # ./ resolves to ./backend because it is is used as base file
    depends_on:
      - backend

  mongo1:
    ports: !override []

  mongo2:
    ports: !override []

  mongo3:
    ports: !override []

  minio:
    ports: !override []
    networks:
      default:
        aliases:
          # https://github.com/minio/minio-js/issues/833
          # presigned url must be requested by going through the same path as the client, ie. through nginx
          # but that is only possible if you have public ip on it ( or changing hosts file locally)
          # for localhost access add to /etc/hosts
          # 127.0.0.1   minio.example.com
          # when accessing minio container on backend service, use the following alias
          - 'minio.example.com'

  rabbitmq:
    ports: !override []
    healthcheck:
      test: ['CMD-SHELL', 'rabbitmq-diagnostics -q ping']
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    ports: !override []
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 10
