x-mongo-environment: &mongo-environment
  - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
  - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
  - MONGO_REPLICA_SET_NAME=${MONGO_REPLICA_SET_NAME}
  - MONGO_DATABASE_NAME=${MONGO_DATABASE_NAME}
  - MONGO_APP_USERNAME=${MONGO_APP_USERNAME}
  - MONGO_APP_PASSWORD=${MONGO_APP_PASSWORD}

x-mongo-replica-common: &mongo-replica-common
  image: mongo
  restart: unless-stopped
  environment: *mongo-environment

services:
  mongo-replica-setup:
    container_name: image-resize-mongo-setup
    image: mongo
    restart: on-failure
    volumes:
      - ./mongo/mongo_setup.sh:/scripts/mongo_setup.sh
    entrypoint: [ "bash", "/scripts/mongo_setup.sh" ]
    environment: *mongo-environment
    depends_on:
      - mongo1
      - mongo2
      - mongo3

  mongo1:
    <<: *mongo-replica-common
    container_name: image-resize-mongo1
    ports:
      - 30001:30001
    command: [ "-f", "/etc/mongod.conf", "--port", "30001", "--keyFile", "/etc/mongo-keyfile", "--replSet", "${MONGO_REPLICA_SET_NAME}", "--bind_ip_all" ]
    volumes:
      - ./mongo/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
      - ./mongo/mongod.conf:/etc/mongod.conf
      - ./mongo/mongo-keyfile:/etc/mongo-keyfile
      - mongo_data1:/data/db
      - mongo_log1:/var/log/mongodb
    healthcheck:
      test: echo 'rs.status().ok' | mongosh admin --port 30001 -u $${MONGO_INITDB_ROOT_USERNAME} -p $${MONGO_INITDB_ROOT_PASSWORD} --quiet | grep 1
      interval: 30s
      start_period: 60s

  mongo2:
    <<: *mongo-replica-common
    container_name: image-resize-mongo2
    ports:
      - 30002:30002
    command: [ "-f", "/etc/mongod.conf", "--port", "30002", "--keyFile", "/etc/mongo-keyfile", "--replSet", "${MONGO_REPLICA_SET_NAME}", "--bind_ip_all" ]
    volumes:
      - ./mongo/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
      - ./mongo/mongod.conf:/etc/mongod.conf
      - ./mongo/mongo-keyfile:/etc/mongo-keyfile
      - mongo_data2:/data/db
      - mongo_log2:/var/log/mongodb
    depends_on:
      - mongo1
    healthcheck:
      test: echo 'rs.status().ok' | mongosh admin --port 30002 -u $${MONGO_INITDB_ROOT_USERNAME} -p $${MONGO_INITDB_ROOT_PASSWORD} --quiet | grep 1
      interval: 30s
      start_period: 60s

  mongo3:
    <<: *mongo-replica-common
    container_name: image-resize-mongo3
    ports:
      - 30003:30003
    command: [ "-f", "/etc/mongod.conf", "--port", "30003", "--keyFile", "/etc/mongo-keyfile", "--replSet", "${MONGO_REPLICA_SET_NAME}", "--bind_ip_all" ]
    volumes:
      - ./mongo/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
      - ./mongo/mongod.conf:/etc/mongod.conf
      - ./mongo/mongo-keyfile:/etc/mongo-keyfile
      - mongo_data3:/data/db
      - mongo_log3:/var/log/mongodb
    depends_on:
      - mongo1
    healthcheck:
      test: echo 'rs.status().ok' | mongosh admin --port 30003 -u $${MONGO_INITDB_ROOT_USERNAME} -p $${MONGO_INITDB_ROOT_PASSWORD} --quiet | grep 1
      interval: 30s
      start_period: 60s

  minio:
    image: minio/minio
    container_name: image-resize-minio # boto does not support underscores in host names
    ports:
      - "9000:9000"
      - "9090:9090" # terminal
    environment:
      - MINIO_ROOT_USER=$MINIO_ROOT_USER
      - MINIO_ROOT_PASSWORD=$MINIO_ROOT_PASSWORD
    volumes:
      - minio_data:/data
    command: [ "server", "--console-address", ":9090", "--address", ":9000", "/data" ]
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

  mc:
    image: minio/mc
    container_name: image-resize-mc
    depends_on:
      - minio
    environment:
      - MINIO_ROOT_USER=$MINIO_ROOT_USER
      - MINIO_ROOT_PASSWORD=$MINIO_ROOT_PASSWORD
    entrypoint: >
      /bin/sh -c "
      mc alias set myminio http://image-resize-minio:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD --api S3v4;
      mc admin trace myminio --verbose;
      "
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: image-resize-rabbitmq
    restart: unless-stopped
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  redis:
    image: redis:7
    container_name: image-resize-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: [ 'redis-server', '--appendonly', 'yes' ]
    volumes:
      - redis_data:/data

#      #
#      #        #  postgres:
#      #        #    image: postgres
#      #        #    restart: unless-stopped
#      #        #    container_name: postgres_dev
#      #        #    ports:
#      #        #      - "5432:5432"
#      #        #    env_file:
#      #        #      - .env.dev.postgres
#      #        #    volumes:
#      #      #      - ./postgres-init-db.sh:/docker-entrypoint-initdb.d/postgres-init-db.sh
#      #      #      - ./postgres_data_dev/:/var/lib/postgresql/data
#
#
#    # TODO containerise celery worker and main app

#      web:
#        build: ./project
#        ports:
#          - 8004:8000
#        command: uvicorn main:app --host 0.0.0.0 --reload
#        volumes:
#          - ./project:/usr/src/app
#        environment:
#          - CELERY_BROKER_URL=redis://redis:6379/0
#          - CELERY_RESULT_BACKEND=redis://redis:6379/0
#        depends_on:
#          - redis
#
#      worker:
#        build: ./project
#        command: celery -A worker.celery worker --loglevel=info
#        volumes:
#          - ./project:/usr/src/app
#        environment:
#          - CELERY_BROKER_URL=redis://redis:6379/0
#          - CELERY_RESULT_BACKEND=redis://redis:6379/0
#        depends_on:
#          - web
#          - redis



volumes:
  mongo_data:
  redis_data:
  rabbitmq_data:
  minio_data:

  mongo_data1:
  mongo_log1:

  mongo_data2:
  mongo_log2:

  mongo_data3:
  mongo_log3: