version: "3.5"
services:
  minio:
    image: minio/minio
    container_name: image-resize-minio # boto does not support underscores in host names
    ports:
      - "9000:9000"
      - "9090:9090" # terminal
    environment:
      - MINIO_ROOT_USER=$MINIO_ROOT_USER
      - MINIO_ROOT_PASSWORD=$MINIO_ROOT_PASSWORD
    volumes:
      - ./minio/data:/data
    command: [ "server", "--console-address", ":9090", "--address", ":9000", "/data" ]
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

  mc:
    image: minio/mc
    container_name: image-resize-mc
    depends_on:
      - minio
    environment:
      - MINIO_ROOT_USER=$MINIO_ROOT_USER
      - MINIO_ROOT_PASSWORD=$MINIO_ROOT_PASSWORD
    entrypoint: >
      /bin/sh -c "
      mc alias set myminio http://image-resize-minio:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD --api S3v4;
      mc admin trace myminio --verbose;
      "
    restart: unless-stopped